import type { TutorialStep } from '../tutorialSteps'

export const CAPTURE_DESK_QUEST_STEPS: TutorialStep[] = [
  {
    id: 'capture-briefing',
    title: 'Capture Desk Briefing',
    body: 'Not every workflow needs Chat. You will wire **Date & Time** and **UUID v4** in parallel to an Agent, then capture the result in **Text Output** — a sink you can copy from.',
    placement: 'center',
    advance: 'manual',
  },
  {
    id: 'capture-mission',
    title: 'No Chat Required',
    body: 'Auto-run tools feed context directly. You launch from the Agent inspector with **Run workflow**, then **Run capture** on the sink.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'manual',
  },
  {
    id: 'capture-drag-datetime',
    title: 'Add Date & Time',
    body: 'Drag **Date & Time** (Essentials). Leave mode on **Format now** — auto-run is on by default.',
    target: 'palette-datetime',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['tool-datetime'],
  },
  {
    id: 'capture-drag-uuid',
    title: 'Add UUID v4',
    body: 'Search **UUID v4** in the palette and drag it on.',
    target: 'palette-uuid-v4',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['tool-uuid-v4'],
  },
  {
    id: 'capture-drag-agent',
    title: 'Add an Agent',
    body: 'Drag an **Agent** to format the parallel context into one log line.',
    target: 'palette-agent',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['agent'],
  },
  {
    id: 'capture-drag-output',
    title: 'Add Text Output',
    body: 'Drag **Text Output** (Essentials) — this is your capture sink.',
    target: 'palette-text-output',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['tool-text-output'],
  },
  {
    id: 'capture-wire',
    title: 'Wire the Desk',
    body: 'Connect **Date & Time Out → Agent Context**, **UUID Out → Agent Context**, and **Agent Out → Text Output In**.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'auto',
  },
  {
    id: 'capture-brief-agent',
    title: 'Brief the Clerk',
    body: 'Click the Agent and set **Role** to something like **ID Clerk**.',
    target: 'inspector-role',
    placement: 'left',
    advance: 'auto',
  },
  {
    id: 'capture-run-agent',
    title: 'Run from Agent',
    body: 'With the Agent selected, click **Run workflow** in the inspector. This runs the upstream tools and the agent — no Chat needed.',
    target: 'inspector-run-agent',
    placement: 'left',
    advance: 'auto',
  },
  {
    id: 'capture-run-capture',
    title: 'Run Capture',
    body: 'Select **Text Output** and click **Run capture** to push the agent output into the log. Copy the result from the inspector.',
    target: 'inspector-run-capture',
    placement: 'left',
    advance: 'auto',
  },
  {
    id: 'capture-epilogue',
    title: 'Captured',
    body: 'You built a no-chat workflow with a capture sink. Load **Examples → ID factory** to remix, or explore header **Examples** for more patterns.',
    placement: 'center',
    advance: 'manual',
  },
]
