import type { TutorialStep } from '../tutorialSteps'

export const ENCODING_QUEST_STEPS: TutorialStep[] = [
  {
    id: 'encoding-briefing',
    title: 'Encoding Briefing',
    body: 'Secret messages 101. You will send text through **Base64 Encode** and **Base64 Decode** before an Agent reads the result — a tiny three-tool pipeline using typed text ports.',
    placement: 'center',
    advance: 'manual',
  },
  {
    id: 'encoding-mission',
    title: 'Clean Slate',
    body: 'Search the palette for **Base64** when you need encode/decode blocks. All ports here are **text** — easy to wire.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'manual',
  },
  {
    id: 'encoding-drag-chat',
    title: 'Start with Chat',
    body: 'Drag **Chat** onto the canvas.',
    target: 'palette-chat',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['chat'],
  },
  {
    id: 'encoding-drag-encode',
    title: 'Add Base64 Encode',
    body: 'Search **Base64 Encode** in the palette (Encoding group) and drag it on.',
    target: 'palette-base64-encode',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['tool-base64-encode'],
  },
  {
    id: 'encoding-drag-decode',
    title: 'Add Base64 Decode',
    body: 'Drag **Base64 Decode** next — we will run text through both.',
    target: 'palette-base64-decode',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['tool-base64-decode'],
  },
  {
    id: 'encoding-drag-agent',
    title: 'Add an Agent',
    body: 'Drag an **Agent** to comment on the round-trip result.',
    target: 'palette-agent',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['agent'],
  },
  {
    id: 'encoding-wire',
    title: 'Wire the Chain',
    body: 'Connect **Chat → Base64 Encode → Base64 Decode → Agent** via **Message**, **In**, **Out**, and **Context** ports.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'auto',
  },
  {
    id: 'encoding-drop-text',
    title: 'Type a Message',
    body: 'In Chat, type: `Hello, encoding!` — the tools will encode then decode before the agent sees it.',
    target: 'chat-input',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'encoding-launch',
    title: 'Run the Chain',
    body: 'Press **send** and confirm the agent receives readable text after the encode/decode round trip.',
    target: 'chat-send',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'encoding-epilogue',
    title: 'Round Trip Complete',
    body: 'You chained manifest tools with typed ports — the same pattern works for hashes, JSON utilities, and other palette blocks. Try **URL detective** or **Voice booth** next, or read the **Guide**.',
    placement: 'center',
    advance: 'manual',
  },
]
