import type { TutorialStep } from '../tutorialSteps'

export const PARALLEL_QUEST_STEPS: TutorialStep[] = [
  {
    id: 'parallel-briefing',
    title: 'Parallel Context Blocks',
    body: 'Tools can feed an Agent **in parallel** with Chat. Wire **Out → Agent Context** — Date & Time, Clipboard, and scrapers all become labeled context the model understands.',
    placement: 'center',
    advance: 'manual',
  },
  {
    id: 'parallel-mission',
    title: 'Your Mission',
    body: 'Build **Chat → Agent** and **Date & Time → Agent** (both into **Context**). Ask “What day is it?” — the Agent sees your message **and** the formatted timestamp.',
    target: 'palette',
    placement: 'right',
    advance: 'manual',
  },
  {
    id: 'parallel-drag-chat',
    title: 'Add Chat',
    body: 'Drag **Chat** onto the canvas.',
    target: 'palette-chat',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['chat'],
  },
  {
    id: 'parallel-drag-datetime',
    title: 'Add Date & Time',
    body: 'Drag **Date & Time** (under Essentials). Set mode to **Format now** in the inspector — auto-run is on by default.',
    target: 'palette-datetime',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['tool-datetime'],
  },
  {
    id: 'parallel-drag-agent',
    title: 'Add Agent',
    body: 'Drag an **Agent** block.',
    target: 'palette-agent',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['agent'],
  },
  {
    id: 'parallel-wire',
    title: 'Wire in Parallel',
    body: 'Connect **Chat Message → Agent Context** and **Date & Time Out → Agent Context**. Both wires go to the same Context port.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'auto',
  },
  {
    id: 'parallel-drop-question',
    title: 'Ask About Today',
    body: 'In Chat, type: `What day is it today?`',
    target: 'chat-input',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'parallel-launch',
    title: 'Send',
    body: 'Press **send**. The Agent receives labeled context blocks — your question plus the current date.',
    target: 'chat-send',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'parallel-epilogue',
    title: 'Context Blocks Unlocked',
    body: 'You wired parallel context modules. Try **Writer\'s room** or **Capture desk** from header **Quests**, **Examples → Research stack**, or read **Guide → Parallel context blocks**.',
    placement: 'center',
    advance: 'manual',
  },
]
