import type { TutorialStep } from '../tutorialSteps'

export const SNACK_QUEST_STEPS: TutorialStep[] = [
  {
    id: 'briefing',
    title: 'Quest Briefing',
    body: 'Listen, rookie. Before you burn credits on fancy cloud AI, you will build something real: a three-node pipeline that reads the web and judges snacks. No key. No server. Just you, the canvas, and questionable life choices.',
    placement: 'center',
    advance: 'manual',
  },
  {
    id: 'mission-board',
    title: 'Your Mission Board',
    body: 'This empty canvas is your crime scene — sorry, workshop. Every great workflow starts as a blank page and ends as something you can brag about in the group chat.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'manual',
  },
  {
    id: 'drag-chat',
    title: 'Summon a Chat Node',
    body: 'Drag **Chat** from the building blocks on the left onto the canvas. This is where you type questions and launch the investigation.',
    target: 'palette-chat',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['chat'],
  },
  {
    id: 'drag-scraper',
    title: 'Recruit a Web Scraper',
    body: 'Now drag **Web Scraper** onto the canvas. It fetches pages **you** choose — only use sites you are allowed to read (check Terms of Service; if you see 403 Forbidden, stop). For this quest, Wikipedia works great. The inspector shows a full safety checklist.',
    target: 'palette-scraper',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['tool-web-scraper'],
  },
  {
    id: 'drag-agent',
    title: 'Hire a Snack Critic',
    body: 'Last recruit: drag an **Agent** onto the canvas. This is the brain that will read the scraped page and deliver a verdict.',
    target: 'palette-agent',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['agent'],
  },
  {
    id: 'wire-nodes',
    title: 'Wire the Investigation',
    body: 'Connect the dots: **Chat → Web Scraper → Agent**. Drag from **Message** (Chat) to **In** (Scraper), then **Out** (Scraper) to **Context** (Agent). Compatible ports glow green while you drag.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'auto',
  },
  {
    id: 'brief-agent',
    title: 'Brief Your Critic',
    body: 'Click the Agent node, then change **Role** in the panel on the right. Try something like **Snack Critic** — give your AI a personality.',
    target: 'inspector-role',
    placement: 'left',
    advance: 'auto',
  },
  {
    id: 'name-quest',
    title: 'Name Your Quest',
    body: 'Rename your workflow at the top (e.g. **Snack Quest**). Every legend needs a title, even if the legend is just you and a pizza article.',
    target: 'workflow-name',
    placement: 'bottom',
    advance: 'auto',
  },
  {
    id: 'drop-evidence',
    title: 'Drop the Evidence',
    body: 'In the Chat box, paste a food URL as your message — try `en.wikipedia.org/wiki/Pizza`. The scraper fetches it when you send (the URL is the payload, not a separate scraper setting).',
    target: 'chat-input',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'launch',
    title: 'Launch Investigation',
    body: 'Hit **send** in the Chat node. With a free OpenRouter key this is fast; without one, a local model may download first — grab a snack. The Activity log shows progress and auto-retries if a model is unavailable.',
    target: 'chat-send',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'epilogue',
    title: 'Case Closed — For Now',
    body: 'You built a real multi-step AI workflow. Try **Pipeline**, **Encoding**, **Parallel**, **Writer\'s room**, **URL detective**, **Voice booth**, or **Capture desk** from header **Quests**, or explore **Examples** for instant wow flows. For faster runs, add a free **OpenRouter** key (**Privacy & keys** in the header).',
    placement: 'center',
    advance: 'manual',
  },
]
