import type { TutorialStep } from '../tutorialSteps'

export const URL_DETECTIVE_QUEST_STEPS: TutorialStep[] = [
  {
    id: 'url-briefing',
    title: 'URL Detective Briefing',
    body: 'Links hide structure. You will parse a URL into JSON with **Parse URL**, then let an Agent explain host, path, and query params in plain language.',
    placement: 'center',
    advance: 'manual',
  },
  {
    id: 'url-mission',
    title: 'Fresh Canvas',
    body: 'Browser tools like **Parse URL** turn messy strings into structured context the model can reason about.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'manual',
  },
  {
    id: 'url-drag-chat',
    title: 'Add Chat',
    body: 'Drag **Chat** onto the canvas.',
    target: 'palette-chat',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['chat'],
  },
  {
    id: 'url-drag-parse',
    title: 'Add Parse URL',
    body: 'Search **Parse URL** in the palette (Browser tools) and drag it on.',
    target: 'palette-parse-url',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['tool-parse-url'],
  },
  {
    id: 'url-drag-agent',
    title: 'Add an Agent',
    body: 'Drag an **Agent** to explain the parsed link.',
    target: 'palette-agent',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['agent'],
  },
  {
    id: 'url-wire',
    title: 'Wire the Detective',
    body: 'Connect **Chat Message → Parse URL In**, then **Parse URL Out → Agent Context**.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'auto',
  },
  {
    id: 'url-drop-url',
    title: 'Paste a Link',
    body: 'In Chat, paste: `https://github.com/zeroclaw/zeroclaw`',
    target: 'chat-input',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'url-launch',
    title: 'Run the Detective',
    body: 'Press **send**. The Agent receives labeled JSON context from Parse URL.',
    target: 'chat-send',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'url-epilogue',
    title: 'Case File Open',
    body: 'Structured URL context unlocked. Try **Voice booth** or **Capture desk** next, or load **Examples → Explain my link**.',
    placement: 'center',
    advance: 'manual',
  },
]
