import type { TutorialStep } from '../tutorialSteps'

export const VOICE_BOOTH_QUEST_STEPS: TutorialStep[] = [
  {
    id: 'voice-briefing',
    title: 'Voice Booth Briefing',
    body: 'Text is fine, but hearing helps. You will chain **Chat → Agent → Speech** so the agent answers, then **Speech** reads it aloud with browser TTS.',
    placement: 'center',
    advance: 'manual',
  },
  {
    id: 'voice-mission',
    title: 'Fresh Canvas',
    body: 'Post-agent tool chains use **Out → In** — the agent output becomes the speech input.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'manual',
  },
  {
    id: 'voice-drag-chat',
    title: 'Add Chat',
    body: 'Drag **Chat** onto the canvas.',
    target: 'palette-chat',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['chat'],
  },
  {
    id: 'voice-drag-agent',
    title: 'Add an Agent',
    body: 'Drag an **Agent** — keep answers short for text-to-speech.',
    target: 'palette-agent',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['agent'],
  },
  {
    id: 'voice-drag-speech',
    title: 'Add Speech',
    body: 'Search **Speech** in the palette and drag it on.',
    target: 'palette-speech',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['tool-speech'],
  },
  {
    id: 'voice-wire',
    title: 'Wire the Booth',
    body: 'Connect **Chat Message → Agent Context**, then **Agent Out → Speech In**.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'auto',
  },
  {
    id: 'voice-configure',
    title: 'Set TTS Mode',
    body: 'Click the **Speech** node. In the inspector, set mode to **Text to speech**.',
    target: 'inspector-speech-mode',
    placement: 'left',
    advance: 'auto',
  },
  {
    id: 'voice-drop-prompt',
    title: 'Ask a Question',
    body: 'In Chat, type: `Say hello in one short sentence`',
    target: 'chat-input',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'voice-launch',
    title: 'Send and Listen',
    body: 'Press **send**. The agent replies, then Speech reads it aloud (check your volume).',
    target: 'chat-send',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'voice-epilogue',
    title: 'On the Air',
    body: 'You added a post-agent tool chain. Try **Capture desk** next, or load **Examples → Voice reply**.',
    placement: 'center',
    advance: 'manual',
  },
]
