import type { TutorialStep } from '../tutorialSteps'

export const WRITERS_ROOM_QUEST_STEPS: TutorialStep[] = [
  {
    id: 'writers-briefing',
    title: "Writer's Room Briefing",
    body: 'Two agents, one pipeline. You will wire **Chat → Writer → Editor** so the first agent drafts and the second polishes — using **Out → Context** between agents.',
    placement: 'center',
    advance: 'manual',
  },
  {
    id: 'writers-mission',
    title: 'Fresh Canvas',
    body: 'Multi-agent chains reuse the same port rules: **Message** and **Context** in, **Out** to the next block.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'manual',
  },
  {
    id: 'writers-drag-chat',
    title: 'Add Chat',
    body: 'Drag **Chat** onto the canvas — your tagline brief starts here.',
    target: 'palette-chat',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['chat'],
  },
  {
    id: 'writers-drag-writer',
    title: 'Add a Writer Agent',
    body: 'Drag an **Agent** for the first draft.',
    target: 'palette-agent',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['agent'],
  },
  {
    id: 'writers-drag-editor',
    title: 'Add an Editor Agent',
    body: 'Drag a second **Agent** — this one polishes the writer output.',
    target: 'palette-agent',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['agent'],
  },
  {
    id: 'writers-wire',
    title: 'Wire the Chain',
    body: 'Connect **Chat Message → Writer Context**, then **Writer Out → Editor Context**.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'auto',
  },
  {
    id: 'writers-roles',
    title: 'Name the Roles',
    body: 'Select each Agent and set **Role** to **Copywriter** and **Editor** (or similar). Both need a job title.',
    target: 'inspector-role',
    placement: 'left',
    advance: 'auto',
  },
  {
    id: 'writers-drop-prompt',
    title: 'Drop the Brief',
    body: 'In Chat, type: `Write a tagline for a browser-based AI workflow builder`',
    target: 'chat-input',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'writers-launch',
    title: 'Send to the Room',
    body: 'Press **send**. The writer drafts, then the editor sharpens — watch the Activity log.',
    target: 'chat-send',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'writers-epilogue',
    title: 'Drafts and Edits',
    body: "You chained two agents with **Out → Context**. Try **URL detective** or **Voice booth** next, or load **Examples → Writer & editor** for a pre-built version.",
    placement: 'center',
    advance: 'manual',
  },
]
